"""Cuts the BMW E90 M3 (S65 V8) recording into the sample set used by scripts/car/car_audio.gd.

Usage:  python3 tools/make_m3_audio.py <s65.mp3>
Needs:  numpy, scipy, soundfile (pip install numpy scipy soundfile)

s65.mp3 – "BMW E90 M3 S65 V8 4.0 Original Stock Exhaust Pure Sound": idle and free-rev blips.
The strongest line is the V8 firing frequency (4th order, rpm = f * 15); idle ~800 rpm.

On-load: the blips rev up far too fast for one clean pull, so three rev-up ramps (~900 -> 2250,
2250 -> 6450 and 6450 -> 7100 rpm) are tracked, warped to a constant line pitch (F_REF_ON) and joined
where their frequencies meet. Off-load: the long, clean rev-down after the last blip (~7000 -> 1000
rpm). Idle: the steady first seconds as a seamless loop. Same tracking/warping as make_r34_audio.py.

Output: assets/audio/m3_*.bin (float32 LE, mono, 22050 Hz) and scripts/car/m3_sound_data.gd.
"""
import sys, os
import numpy as np
from scipy import signal
from make_r34_audio import (OUT_RATE, load, track, warp, lowpass, resample, crossfade_join, make_loop,
                            table, fade, write_bin)

ORDER = 4.0          # V8 firing frequency
F_REF_ON = 90.0
F_REF_OFF = 90.0

# (start s, end s, initial line frequency Hz) – rev-up ramps, joined in this order
RAMPS = [(17.86, 18.20, 61.0), (13.56, 14.07, 150.0), (24.93, 25.08, 420.0)]
DECAY = (25.12, 29.8, 470.0)
IDLE = (0.3, 5.7)


def main():
    path = sys.argv[-1]
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = os.path.join(root, "assets", "audio")
    os.makedirs(out_dir, exist_ok=True)

    m, fs = load(path)
    ml = lowpass(m, fs, 10500)

    on, on_f = None, None
    for (a, b, f0) in RAMPS:
        t, f = track(m, fs, a, b, f0, lo=0.95, hi=1.08, harm=(1, 2), smooth=15, hop=120)
        f = np.maximum.accumulate(f)
        if on_f is not None:
            # start where the previous ramp ended
            keep = f > on_f[-1]
            t, f = t[keep], f[keep]
        seg, seg_f = warp(ml, fs, t, f, F_REF_ON)
        if on is None:
            on, on_f = seg, seg_f
        else:
            n = int(0.012 * OUT_RATE)
            on = crossfade_join(on, seg, n)
            on_f = np.concatenate([on_f[:-n], seg_f])
    on = fade(on, 300, 300)

    t_dn, f_dn = track(m, fs, *DECAY, lo=0.9, hi=1.06, harm=(1, 2), smooth=41)
    f_dn = np.minimum.accumulate(f_dn)
    off, off_f = warp(ml, fs, t_dn, f_dn, F_REF_OFF)
    off = fade(off, 300, 300)

    idle = resample(ml[int(IDLE[0] * fs):int(IDLE[1] * fs)], fs)
    idle = make_loop(idle, int(0.35 * OUT_RATE))
    fq, P = signal.welch(ml[int(IDLE[0] * fs):int(IDLE[1] * fs)], fs, nperseg=32768)
    sel = (fq > 45) & (fq < 65)
    idle_rpm = float(fq[sel][np.argmax(P[sel])]) * 60.0 / ORDER

    rms = lambda a: float(np.sqrt(np.mean(a ** 2)))
    # match the R34 levels (on-load rms ~0.3); the few blip peaks above that are soft-limited
    on *= 0.3 / rms(on)
    on = 0.95 * np.tanh(on / 0.95)
    off *= (0.64 * rms(on)) / rms(off)
    off = 0.95 * np.tanh(off / 0.95)
    idle *= (0.45 * rms(on)) / rms(idle)
    print("engine: on %.0f-%.0f rpm (%.2f s), off %.0f-%.0f rpm (%.2f s), idle %.0f rpm" % (
        on_f.min() * 15, on_f.max() * 15, len(on) / OUT_RATE, off_f.min() * 15, off_f.max() * 15,
        len(off) / OUT_RATE, idle_rpm))

    write_bin(os.path.join(out_dir, "m3_engine_on.bin"), on)
    write_bin(os.path.join(out_dir, "m3_engine_off.bin"), off)
    write_bin(os.path.join(out_dir, "m3_idle.bin"), idle)

    step = 64
    gd = [
        "extends RefCounted",
        "## Generated by tools/make_m3_audio.py – sample tables for the M3 (S65 V8) engine sound.",
        "## *_F tables: tracked line frequency (Hz) every %d samples of the matching buffer." % step,
        "",
        "const PREFIX := \"m3\"",
        "const RATE := %d" % OUT_RATE,
        "const ON_ORDER := %.2f" % ORDER,
        "const OFF_ORDER := %.2f" % ORDER,
        "const F_REF_ON := %.2f" % F_REF_ON,
        "const F_REF_OFF := %.2f" % F_REF_OFF,
        "const F_REF_TURBO := 1.0",
        "const TABLE_STEP := %d" % step,
        "const GAIN := 1.55",
        "const IDLE_RPM := %.1f" % idle_rpm,
        "const LIFT_COUNT := 0",
        "const ON_F := %s" % table(on_f, step),
        "const OFF_F := %s" % table(off_f, step),
        "const SPOOL_F := []",
        "",
    ]
    with open(os.path.join(root, "scripts", "car", "m3_sound_data.gd"), "w") as f:
        f.write("\n".join(gd))
    print("done")


if __name__ == "__main__":
    main()
